### ISSUE TITLE
Document ES_MEM_LIMIT on Troubleshooting, ElasticSearch pages

### ISSUE THREAD

**Issue by katmoody** [humanmade/altis-documentation#113]
Altis has an environment variable that can be set to  change the default memory limit for ElasticSearch called `ES_MEM_LIMIT` which needs documented on the Troubleshooting and ElasticSearch pages within documentation. 

- [x] Confirm text to add to each page
- [x] Troubleshooting page edits
- [x] ElasticSearch page edits

_Adding this per note added to Dashboard ticket: https://dashboard.altis-dxp.com/next/#/support/ticket/2163/_ 

---

Because of the high memory usage for most CI platforms (eg. Travis, Circle or GitHub Actions.), when they are being used we should update the memory limit or the local server won't run successfully. 

Using this variable with the `composer server start` command, users can update the memory limit for the current session only; it won't change the variable permenantly: 

`ES_MEM_LIMIT=2g composer server start`

Users can also define that environment variable on the container's config file if they wanted a permanent fix. For instance, editing or adding the variable to the "environment" section of the [/docker-compose.yml ](https://github.com/humanmade/altis-local-server/blob/master/docker/docker-compose.yml) Altis Local Server setup. 

@roborourke - did I get all the main notes right?

**Comment by roborourke** [comment]
@katmoody also need to mention this might be necessary for users on Ubuntu but I think that about covers it

**Comment by katmoody** [comment]
I've added the edits for both sections and created a PR (linked above) 🎉
