### ISSUE TITLE
Add internal link for support

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-documentation#116]
Documentation should support a `support://new` link which prefills the stack ID if available.

The link should be rewritten to `https://dashboard.altis-dxp.com/#/support/new`

If we know the stack name eg. the environment is staging, development, or production - we can use `Altis\get_environment_name()` to get this.

The link should then have `?applications[]=<stack name>` appended to it.

**Comment by roborourke** [comment]
Fixed in #156
