### ISSUE TITLE
Add ability to add additional documentation "sets"

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-documentation#122]
Right now, all documentation is together in one "set", which is for developer docs.

To empower developers to build other types of documentation (project-specific, user), we should add the ability to add additional "sets".

The "set" we currently have would become the technical documentation set.

### Additional context

Internally right now, we have two object types in a hierarchy like this:

* Group (aka module, or "Getting Started" or "Guides")
  * Page

(Pages can have parents, but that's contained within its own hierarchy.)

Custom code can add custom groups or pages. Altis' built-in code automatically generates groups for each module, and then parses each module's Markdown files into pages under that module.

The Documentation page takes all groups and renders them onto the page.

What I'd like to propose is adding one more level of hierarchy above groups, called a "set". Out-of-the-box, we'd have a dev-docs set. Altis' built-in code would add the automatic groups to that set, and the Documentation page would take groups from that set specifically.

The hierarchy would look like this:

* Set (e.g. `dev-docs`)
  * Groups
    * Pages

Sets wouldn't be exposed to the user, they're more for internal organisation of groups.

This would allow building other types of documentation using the infrastructure we already have, but without adding new groups and pages to the built-in UI. i.e. I could add a project set, add some groups for different types of user docs, and then choose to render that on some other page myself, without it rendering on the default admin page.

### Acceptance Criteria

* [x] Documentation module has a core `Set` object which is a list of `Group`s
* [x] `Set` object has a title
* [x] New top level admin menu section for "Documentation", each set is added a sub page
* [x] Altis creates a `dev-docs` set automatically on local environments called "Developer Documentation"
* [x] Automatically generated groups are added to the `dev-docs` set
* [x] "Documentation" top level page in the admin only renders docs from first available set
* [x] Documentation page views are tracked using Altis Telemetry, set, group and page titles

### Additional criteria after review:

- [x]  If no sets are found (non local/dev environment and no additional sets), don't render documentation menu
- [x]  If additional sets are added, add the Documentation Menu and add the additional sets as sub pages.
- [x]  Always render the first set found: dev-docs on local/dev environment, first additional set if any are added
- [x]  If someone wants to add their documentation set to another menu, the can do so by both adding to the default array of sets. And adding their own menu/submenu and still use the provided functionality/filters to have the system render their docs.

**Comment by roborourke** [comment]
This covers what we want conceptually but could you provide some acceptance criteria in terms of what inputs should be supported and what outputs? Not sure if the scope of this includes anything beyond building an array of docs from a directory at the moment.

**Comment by rmccue** [comment]
Internally right now, we have two object types in a hierarchy like this:

* Group (aka module, or "Getting Started" or "Guides")
  * Page

(Pages can have parents, but that's contained within its own hierarchy.)

Custom code can add custom groups or pages. Altis' built-in code automatically generates groups for each module, and then parses each module's Markdown files into pages under that module.

The Documentation page takes all groups and renders them onto the page.

What I'd like to propose is adding one more level of hierarchy above groups, called a "set". Out-of-the-box, we'd have a `dev-docs` set. Altis' built-in code would add the automatic groups to that set, and the Documentation page would take groups from that set specifically.

The hierarchy would look like this:

* Set (e.g. `dev-docs`)
  * Groups
    * Pages

Sets wouldn't be exposed to the user, they're more for internal organisation of groups.

This would allow building other types of documentation using the infrastructure we already have, but without adding new groups and pages to the built-in UI. i.e. I could add a `project` set, add some groups for different types of user docs, and then choose to render that on some other page myself, without it rendering on the default admin page.

So, acceptance criteria hence would be:

* [ ] Documentation module has a core Set object
* [ ] Altis creates a `dev-docs` set automatically
* [ ] Automatically generated groups are added to the `dev-docs`set
* [ ] "Documentation" page in the admin only renders groups from the `dev-docs` set
* [ ] Built-in documentation groups and pages are rendered on the "Documentation" page
* [ ] Groups and pages added to other sets are **not** rendered on the Documentation page

**Comment by katmoody** [comment]
I'm trying to understand the best way to prepare user documentation if we were to make them another 'set' - would they go in a different repo or within the same documentation module (just as a different set)?

**Comment by roborourke** [comment]
The modules give us some architecture in the sense that we use their names. For all user docs that don’t neatly fit into a module we could put them here in the same way we do with the `other-docs` folder that adds the guides and getting started bits

**Comment by roborourke** [comment]
I updated the acceptance criteria based on a conversation with the team, let me know if you have any thoughts & request any clarification or changes.

There will be a follow up issue to create the user docs "Set" and handling for user docs in Altis modules.

**Comment by shadyvb** [comment]
@mikelittle I assigned this ticket to you tentatively as you started work on one of the other tickets in the same Epic. Hope that's okay.

**Comment by roborourke** [comment]
Done in #365
