### ISSUE TITLE
Add guide for setting up dependabot

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-documentation#129]
Dependabot is a highly useful tool for managing `package-lock.json` and `composer.lock` file changes, highlighting when updates are available and automating those updates given developer approval. It also has the advantage of handling conflicts nicely by rebasing it's PRs automatically when the target branch changes, removing a potential headache for devs.

https://dependabot.com/

**Comment by roborourke** [comment]
@joehoyle @rmccue in the same way we include a few files via the dev tools and cms installer packages what are your thoughts on adding a default Dependabot config out of the box?

**Comment by rmccue** [comment]
Sounds good to me, I think we may have even discussed that previously?
>
>

-- 
Ryan McCue
Director of Engineering

**Comment by joehoyle** [comment]
Yeah we should do this!

--

Joe Hoyle

CTO
Human Made
