### ISSUE TITLE
Add a guide for running CLI commands on both local environments

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-documentation#155]
We have docs for running CLI commands on Local Server but not Local Chassis. Although it would somewhat duplicate docs a general guide on running WP CLI commands with common uses cases and examples.

Possible use-cases:

- Database imports
- Search replace
- Updating posts
- Exploring cron events
- Indexing elasticsearch

**Comment by mikelittle** [comment]
Completed here  https://docs.altis-dxp.com/local-server/cli/
Chassis no longer used.
