### ISSUE TITLE
Add more documentation on features of X-Ray in Vantage

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-documentation#157]
**Feedback from Altis dev Satisfaction Survey on X-Ray feature in Vantage:** 

"UI of Logs and searching X-ray interface is confusing. It’s still not obvious what the search syntax is and I always look up the docs to find out. I didn't get how to use the syntax at first from reading it. There's nothing wrong with the help docs themselves, just that an expanded prose explanation of what kind of information you can get from Xray and how to find it would be nice."

**Comment by rmccue** [comment]
Documentation has been improved since this was filed.
