### ISSUE TITLE
Example dependabot config is invalid

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-documentation#162]
See this issue that dependabot creates automatically on a repo https://github.com/humanmade/dormakaba/issues/385

**Comment by roborourke** [comment]
@pdewouters given that repo is private it might be handy to paste some of the output here for future reference, or the changes you used to fix it would be handy too. I think we may have some problem with incompatibilities between the built in GH version and the legacy dependabot app.

**Comment by roborourke** [comment]
Looks you copied that example config into `.dependabot/config.yml` rather than creating a `dependabot.yml` file into the root directory of the project. There is a still an issue with the example in the docs though. Will get that patched now

**Comment by pdewouters** [comment]
Ah right, thanks. I didn't notice that. I just thought I should update the existing config. Maybe we could make a note on that page

**Comment by roborourke** [comment]
It does say to put it in the project root and what to name the file. Could call out what to do with the legacy version if you have one I suppose

**Comment by pdewouters** [comment]
Feel free to close
