### ISSUE TITLE
External link improvements

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-documentation#19]
Some documentation links will be to external sources. It's common to indicate these links differently with a little arrow icon or similar as seen on Wikipedia for example.

In addition the title attribute can be used on the link to state that it's an external link.

**Comment by joeleenk** [comment]
I recently learned from Rian that the title attribute is discouraged now:
https://github.com/humanmade/encompass/pull/1191

We can add the little external link icon and screen reader text, if the link is opening a new window, though for accessibility it is preferred not to open in a new window. 

Did you want to check for external links with JS or CSS, or try to add the icon manually to each? I like the idea of doing it with CSS ([option 3 here](https://css-tricks.com/snippets/jquery/target-only-external-links/)), but we'd have to have a programatic way of getting the site URL for docs in the dashboard.

**Comment by roborourke** [comment]
If we’re going to add screen reader text for those links then we can
perhaps add a class name that use in the CSS. It’ll be easier to do that on
the PHP side as you say because we need to know the current URL.
-- 
Robert O'Rourke
Product Engineer
Human Made Limited <https://humanmade.com/>

<https://humanmade.com/enterprise-wordpress-newsletter/?utm_source=email&utm_campaign=email_ro>

*Get the inside track on enterprise WordPress news in your inbox once a
month
<https://humanmade.com/enterprise-wordpress-newsletter/?utm_source=email&utm_campaign=email_ro>.
Make more informed decisions starting today.*

**Comment by rmccue** [comment]
I think this has been OK so far, so let's close this out unless we hear from more people that it's confusing.
