### ISSUE TITLE
Document the `wp altis migrate` command better

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-documentation#251]
We don't have any documentation about the `migrate` CLI command, how to hook into the migration command, or what functions/types of migrations can be done out of the box.

**Acceptance criteria**
- [x] Add documentation page for `wp migrate` command
- [x] Document sub-commands and OOTB integrations with `wp migrate` (e.g. Yoast SEO migration https://github.com/humanmade/altis-seo/pull/84)
- [x] Document how to hook into the migration hooks so custom migration scripts can be integrated into a `wp migrate` execution.

**Comment by missjwo** [comment]
@mikelittle  todo: check if it still a function we have in Altis

**Comment by mikelittle** [comment]
Closing this as the existing page https://docs.altis-dxp.com/core/cli-command/ covers the requirements of this ticket.
