### ISSUE TITLE
De-emphasise manual code review process from documentation

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-documentation#276]
As we have now transitioned to automated code review, we should de-emphasise the manual code review process from the documentation to avoid any confusion for new customers.

The manual code review process is documented on [the main code review guide page](https://docs.altis-dxp.com/guides/code-review/). The page should show the automated code review process first, and document the manual process only for legacy customers.

Acceptance criteria:

* [ ] As a developer on an Altis project, when I view the code review documentation, I should see the most relevant documentation about automated code review first
* [ ] As a developer on a legacy project, when I view the code review documentation, I should see the legacy review process documented

**Comment by roborourke** [comment]
@rmccue how are we defining a legacy project here, I'm not sure how we could conditionally show docs or infer whether a project is legacy or not unless this is just about how far back / if we backport it.

**Comment by rmccue** [comment]
@roborourke let's just direct people on legacy projects to older versions of the docs instead
