### ISSUE TITLE
V10 Upgrade guide incomplete bullet point

### ISSUE THREAD

**Issue by Sephsekla** [humanmade/altis-documentation#335]
Great work on the new version! Just spotted a very minor issue when reading through the upgrade guide:

`wp elasticpress request allows you to execute arbitrary requests from the command line to aid with` 

Looks like the end of this point has been cut off somewhere along the line.

See: https://docs.altis-dxp.com/guides/upgrading/v10/#elasticpress-36-1

My best guess is maybe `wp elasticpress request allows you to execute arbitrary requests from the command line to aid with debugging` or maybe just `wp elasticpress request allows you to execute arbitrary requests from the command line`, given the context.

**Comment by roborourke** [comment]
Less haste more speed as they say, thanks for the report!
