### ISSUE TITLE
Sorting of upgrade docs is off

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-documentation#339]
Versions are sorted textually, so v10 comes before v1.

![image.png](https://images.zenhubusercontent.com/570267946caf56c9d38f3a03/4cc18f57-58d0-4920-b3b7-954e25976776)

Acceptance criteria:

- [ ] Upgrade documentation shows versions in correct order.

**Comment by JadeEngelbrecht** [comment]
Hope its ok to tag this on here, I noticed that the upgrades listed on the right do not include 9 and 10.

![Screenshot 2022-02-16 at 11 39 44](https://user-images.githubusercontent.com/42337176/154237366-519e2387-510e-429d-a401-f5c9d371ddc9.png)

**Comment by shadyvb** [comment]
Yeah, probably better to remove those as already have them in the sidebar.
