### ISSUE TITLE
Clarify how Altis config inheritance work in documentation

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-documentation#346]
We need to explicitly document how config inheritance work in Altis config, between default, general, and environment specific tree.

### Acceptance criteria
- [x] Altis docs reference how config inheritance work, with multiple examples / cases.

**Comment by mikelittle** [comment]
Having read through the page here https://docs.altis-dxp.com/getting-started/configuration/, I believe the current documentation covers the requirements of this ticket.
Closing.
