### ISSUE TITLE
Upgrade guide for v10 doesn't describe changes to module registration API

### ISSUE THREAD

**Issue by goldenapples** [humanmade/altis-documentation#381]
Before https://github.com/humanmade/altis-core/pull/314, the syntax for registering a module which was enabled by default was 
```
[ 'enabled' => true ]
```

After that change (which landed as part of Altis v10), the configuration object needs to be rewritten as 
```
[ 'defaults' => [ 'enabled' => true ] ]
```
and registering a module with the previous syntax will make it disabled by default.

I would consider this a breaking change, and would like to see it called out in the upgrade guide. On a project I'm working on, I spent a while trying to figure out why custom functionality stopped worked after the upgrade to v10, only to find this was the culprit.

Acceptance criteria:
- [x] Make sure that the v10 Guide is updated with this information under the "Breaking changes" section (edit on master, backport to v10)
- [x] Re-add the custom module documentation removed in this commit to the core module https://github.com/humanmade/altis-documentation/commit/7a90777b74b6ced7a9b89f7b95d36997c5d56450 (backport to v10)

**Comment by roborourke** [comment]
Fixed in #392
