### ISSUE TITLE
Absolute link to public docs website instead of relative link to docs.

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-documentation#395]
"Custom functionality on top of the Altis platform is implemented via WordPress plugins, and Altis is generally compatible with most WordPress plugins. (Subject to our [cloud environment limitations]().)"

https://github.com/humanmade/altis-documentation/blob/master/other-docs/getting-started/README.md

The link "cloud environment limitations" points to the public docs site (`https://docs.altis-dxp.com/cloud/limitations/`) instead of linking to `docs://cloud/limitations.md`

**Comment by robindevitt** [comment]
Merged and closed out now
