### ISSUE TITLE
Docs admin page title shows wrong page title on group parent page

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-documentation#397]
Steps to reproduce:
1. Go to the getting started guide in the developer docs in the admin
2. View the `<title>` tag source

We should see the page title "Getting Started", instead it shows the title of the last page in the group "For WordPress Developers".

Additionally I think the page title should have the documentation set title appended to it, e.g. "Getting Started / Developer Documentation".

Acceptance criteria:

- [x] Correct page title is shown on group parent pages and all docs pages regardless of location in page or group hierarchy
- [x] Page has the documentation set title appended to it

**Comment by roborourke** [comment]
Is that actually Altis v11 or the current development version?

**Comment by robindevitt** [comment]
I have it on a V11 install, also seeing the same on current development vesion
