### ISSUE TITLE
Document what php version should be listed.

### ISSUE THREAD

**Issue by robindevitt** [humanmade/altis-documentation#417]
Slack thread for reference : https://hmn.slack.com/archives/C5WSNGC9F/p1661867523037569

The reported error:
>The configured PHP version “7.4.13” is not supported.
Try one of the following:
>- 8.0
>- 7.4

Setting the `local-server` php value to `7.4.13` in your `composer.json` file, causes the above error.

#### What not to do
```json
"extra": {
    "altis": {
        "modules": {
            "local-chassis": {
                "php": "7.4.13"
            },
            "local-server": {
                "php": "7.4.13"
            }
        }
    }
}
```

#### Acceptance criteria
The values for `local-server` and `local-chassis` for php in `composer.json` should be noted that
- Only major and minor versions should be listed.
- The patch version should not be listed.

**Comment by veselala** [comment]
@robindevitt will work on the wording here
