### ISSUE TITLE
Search results heading shows `+` symbols for spaces

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-documentation#418]
Example: https://docs.altis-dxp.com/v12/s/?search=migrate+yoast+seo

The heading on the page says `Showing results for “migrate yoast+seo”`. Seems to affect search phrases that contain more than one space.

**Comment by rmccue** [comment]
Guessing we have some sort of regex replace without `/g` here

**Comment by mikelittle** [comment]
I think this is fixed with the rebuilt search functionality. Please re-open if the problem happens again.
