### ISSUE TITLE
Undefined array key "page"

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-documentation#421]
This module triggers a PHP notice on the Settings -> Reading screen in the admin area. With PHP 8 in use this is a PHP warning.

```
Undefined array key "page" in vendor/altis/documentation/inc/ui/namespace.php:142
```

The error can be seen on the Altis Demo site at https://demo.altis.cloud/wp-admin/options-reading.php

**Comment by robindevitt** [comment]
Thanks for reporting this issue @johnbillion.
