### ISSUE TITLE
Apt package manager instructions missing component

### ISSUE THREAD

**Issue by CoreyBenefiel** [humanmade/altis-documentation#454]
https://docs.altis-dxp.com/local-server/windows/#install-altis-prerequisites

`$ sudo apt install php-cli php-curl` is missing php-zip.

Instruction should be `$ sudo apt install php-cli php-curl php-zip`

**Comment by roborourke** [comment]
Also needed `php-xml`

**Comment by missjwo** [comment]
update has been merged in. Closing.
