### ISSUE TITLE
Update the LTS page with latest release information

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-documentation#470]
The [Long Term Support page](https://docs.altis-dxp.com/guides/long-term-support/) isn't intended to specifically document currently supported versions, but the diagram shows Altis versions from 1 to 8 and therefore doesn't provide information about currently supported versions. It would be nice to:

### Acceptance criteria

* [ ] Add a caption to the diagram to explain that it's a generic image
* [ ] Link to [the Release page](https://docs.altis-dxp.com/releases/) which lists currently supported versions

**Comment by rmccue** [comment]
I have the original Whimsical doc if we want to change this but I don't think we really need to change the diagram itself. We should link the page though for sure.

**Comment by kovshenin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-documentation/470?planning-poker) with Zenhub @ferschubert-hm @jerico @mikelittle @wisyhambolu

**Comment by missjwo** [comment]
@mikelittle  whats left to do on this?

**Comment by mikelittle** [comment]
@missjwo This is complete but there are three back port PRs triggered from this that were stuck. One I've now merged, but the other two had problems with travis and HM Linter.
I've re-run the travis one, but the HM linter is still stuck.Been running for 2 days and I can't see away to cancel/re-run it.

**Comment by mikelittle** [comment]
I eventually ignored the stuck linter (it's only a documentation file anyway) and merged all three PRs
