### ISSUE TITLE
Document using RC versions of upcoming modules

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-documentation#49]
Spun out of https://github.com/humanmade/platform-documentation/pull/44, we should document the process of upgrading to an RC of a module version.

**Comment by roborourke** [comment]
This will look like the following:

```json
{
    "require": {
        "altis/altis": "^1.0.0",
        "altis/cms": "@RC",
        "altis/security": "~1.2.0@RC"
     }
}
```

The result will be:

- Stable 1.0.x releases of Altis
- RC 1.x.x releases of Altis CMS
- RC 1.2.x releases of Altis Security
