### ISSUE TITLE
Add Edit on Github links

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-documentation#50]
One of the features on the previous iteration of docs was a link to edit the file on Github. This could be phrased better eg. a link at the bottom saying "Found a typo or error? Edit this page on Github".

In addition we could have a link saying "Is there something missing or unclear? Create an issue" to prepopulate a new issue screen on the relevant repo.

Acceptance criteria:

- [ ] Add an edit on github link to the footer of all docs pages following the design here https://github.com/humanmade/altis-documentation/issues/50#issuecomment-541632502
  - The link should open the relevant document on Github in edit mode eg https://github.com/humanmade/altis-documentation/edit/master/other-docs/welcome.md
  - The `master` branch part should reflect the current version branch if possible eg. `v2-branch`
- [ ] Add a link below the above with same design and the text: "Have a question or suggestion? Create an issue on GitHub"
  - The link should open the new issue form on the module's repo with the following prepopulated ([using query strings to prepopulate issues](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters)):
    - title: ""
    - content: "<link to the .md file at the current version/commit of the doc>
       "
    - labels: documentation

**Comment by roborourke** [comment]
@grarighe can we get a bit of design feedback here? Eg. top or bottom of the page.

**Comment by rmccue** [comment]
Let's bump this to v3 as we're in feature freeze and don't really have design direction.

**Comment by rmccue** [comment]
Moved back to In Research as it's awaiting design.

**Comment by grarighe** [comment]
How about something simple as:

<img width="419" alt="Screenshot 2019-10-14 at 13 42 54" src="https://user-images.githubusercontent.com/17759455/66748904-b15aed80-ee88-11e9-93a0-c814d9d4f4ec.png">

To keep it simple we could show this below the content, with 96px padding above and below to give it enough white space so it's visually separate. 

Mock-up: https://invis.io/GCUD0QSQNHU#/388495637_Documentation-02-Toc-Gh

FYI we are already testing a [widget](https://github.com/humanmade/platform-site/issues/406) on the site to get readers to rate content on the page and recommend improvements.
