### ISSUE TITLE
Add v15 and PHP 8.2 to compatibility chart

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-documentation#503]
https://docs.altis-dxp.com/guides/updating-php/#altis-compatibility-chart is missing v15 and PHP 8.2

**Comment by kadamwhite** [comment]
@rmccue In the absence of an actual docs change, what IS the support matrix for v15, is 8.0 still supported or is it only 8.1 or 8.2?

**Comment by rmccue** [comment]
@kadamwhite We mirror the PHP official support timelines; 8.0 is supported until November, so it will not be supported for the full duration of the v15 release (which is supported until April 2024): https://www.php.net/supported-versions.php

For future proofing, we'd recommend 8.1 or 8.2 (which are supported beyond the end of v15), but if you plan on upgrading in the meantime, 8.0 would be fine.

**Comment by johnbillion** [comment]
[The upgrade guide for v15 states](https://docs.altis-dxp.com/guides/upgrading/v15/#php-82):

> Altis v15 fully supports PHP 8.2 in both local and cloud environments

This differs from the v15/8.2 cell in the compatibility table which says _Experimental_.

Can the support for 8.2 on v15 be clarified?

**Comment by missjwo** [comment]
We’re past V15. Closing.
