### ISSUE TITLE
Support `mailto` links should be replaced with new ticket link

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-documentation#551]
### Description

As per a comment here https://github.com/humanmade/altis-documentation/pull/547#issuecomment-1752869742, the current `mailto` links in the documentation should really link to the new ticket URL in the dashboard.

@rmccue That link, doesn't work on the live docs site, https://docs.altis-dxp.com/. Can we redirect it to somewhere sensible there?

### Acceptance Criteria

- [ ] All `mailto` links to be replaced across all Altis documentation by the support form link `support://new`

---

### Ready for Work Checklist

Is this ticket ready to be worked on? See
[the Play Book Definition of Ready](https://playbook.hmn.md/play/product/definition-of-ready/)

- [x] Is the title clear?
- [x] Is the description clear and detailed enough?
- [x] Are acceptance criteria listed?
- [x] Have any (potential) dependencies been identified?
- [x] Is an estimate or time box assigned?
- [x] Is a priority label assigned?
- [ ] Is this ticket added to an epic? (Optional)

### Completion Checklist

Is this ticket done? See
[the Play Book Definition of Ready](https://playbook.hmn.md/play/product/definition-of-ready/)

- [ ] Has the acceptance criteria been met?
- [ ] Is the documentation updated (including README)?
- [ ] Does any code/documentation meet project standards?
- [ ] Are automatic tests in place to verify the fix or new functionality?
- [ ] Or are manual tests documented (at least on this ticket)?
- [ ] Are any Playbook/Handbook pages updated?
- [ ] Has a new module release (patch/minor) been created/scheduled?
- [ ] Have the appropriate `backport` labels been added to the PR?

**Comment by rmccue** [comment]
@mikelittle They should all point to `support://new` which will work consistently across every environment they're displayed: https://docs.altis-dxp.com/documentation/linking/#link-to-support

**Comment by ferschubert-hm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-documentation/551?planning-poker) with Zenhub @jerico @kovshenin @mikelittle @wisyhambolu

**Comment by ferschubert-hm** [comment]
@mikelittle the change is to replace `mailto` with the support link? For example I have identified these `mailto` occurrences https://github.com/search?q=repo%3Ahumanmade%2Faltis-documentation%20mailto&type=code should these then be changed to `mailto`?
