### ISSUE TITLE
Update configuration guide on distinction between config & db

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-documentation#57]
Altis provides some configuration options which override user-configurable options which are displayed in the UI. When these configuration options are set via the composer.json config, the UI options are not used, and the database is never checked.

We should make this clearer.

Add the following to the configuration guide
> In the event that something can be configured that can also edited via the admin UI the configuration in `composer.json` takes precedence.

## Original description
Some feedback we've had so far indicated that we should clarify when adding settings in the config there is no change to or interaction with the database. In the event that something can be configured that can also edited via the admin UI the configuration in `composer.json` takes precedence.

Props @johnbillion

**Comment by robindevitt** [comment]
The configuration guide needing to be updated, is it [this guide](https://docs.altis-dxp.com/getting-started/configuration/) from the Altis Documentation?

**Comment by roborourke** [comment]
@robindevitt yep, that's the one :)

**Comment by robindevitt** [comment]
@roborourke I have setup a [PR](https://github.com/humanmade/altis-documentation/pull/318/files) and requested a review from you. Mainly confirmation on the location I chose to put the additional content.

**Comment by roborourke** [comment]
Fixed in https://github.com/humanmade/altis-documentation/issues/318
