### ISSUE TITLE
Suggestion : A separate document for modules listing

### ISSUE THREAD

**Issue by pushpakpop** [humanmade/altis-documentation#65]
A separate page/document which list all the modules/submodules being used in Altis, along with the actual module/submodule name-string that is used in composer.json file for configurations would be great.

Currently, have to check individual module documentation to check for available submodules and their name to be able to add configurations accordingly and not all submodules names are listed out in the documentation.

**Comment by rmccue** [comment]
One thing that might help with this is the about pages being added in v2: https://github.com/humanmade/altis-core/pull/33

**Comment by rmccue** [comment]
Closing, as this is handled by the about page now.
