### ISSUE TITLE
Add feedback capabilities to docs

### ISSUE THREAD

**Issue by grarighe** [humanmade/altis-documentation#76]
I see that we're considering to work on many enhancements of the documentation, but there is one feature that I really think we should fast-track: a way for readers to leave feedback. This would be only a small part of a greater effort to build a proper customer feedback system.

Why is that important? We should collect customer feedback to get possibly useful insights to enhance our product, our users' experience and optimise our sales funnels. We need to start that conversation and the easiest way is to implement (build or integrate) simple tools to gather spontaneous feedback.

**Opportunities in the docs:**
- We could ask users if they found the content useful 
- We could ask how we could improve it 
- We could ask if they have specific suggestions about the feature described in the content

this way we could easily find out more about our haters and fans and have more data points when making decisions and prioritising what to work on next. This could be even the way we find the 'champions' that can help us in our research.

Depending on the approach we choose, we could extend this functionality to the whole Altis site (e.g with a widget) and I know we discussed that before, so if that's on hold for any reason, maybe we could consider at least building something in the docs. The MVP could be a simple multi-step form at the bottom of the page.

What do you guys think?

**Comment by grarighe** [comment]
For the time being I've added [a Hotjar Poll widget ](https://github.com/humanmade/platform-site/issues/406).

**Comment by roborourke** [comment]
I think we can stage this, starting with providing links to create a pre-populated issue on Github using work that will be done in #50 

I'll update the main issue with some acceptance criteria for what the first iteration of this should look like.

**Comment by roborourke** [comment]
2nd thoughts I think we should plan out a simple interactive feature for doing this in future. Using GitHub and Altis support doesn't really capture the answer to whether people found the docs useful or not and require a higher level of engagement to get feedback.

**Comment by rmccue** [comment]
Closing this out, won't do.
