### ISSUE TITLE
Add login information for Chassis setup

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-documentation#81]
When setting up a new Altis project using Chassis, it's not clear from the [Getting Started](https://www.altis-dxp.com/resources/docs/getting-started/) guide how to access the WordPress admin. 

The [Chassis docs](http://docs.chassis.io/en/latest/quickstart/) state:

> The default login credentials are `admin` and `password` and the login URL is http://vagrant.local/wp/wp-admin.

In this case, the credentials are correct but the location is wrong - the admin is at `/wp-admin/`.

When we're setting up the site using [Local Server](https://www.altis-dxp.com/resources/docs/local-server/), the login details are included as part of the setup. 

> Visit `/wp-admin/` and login with `admin` / `admin` to get started!

I suggest we add the same for the Chassis.

**Comment by rmccue** [comment]
It displays in the output from the `start` command, but easy to miss. Let's add to the docs too :) Thanks for the PR!
